FreresHeureux/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('wine/', include('wineList.urls', namespace='wineList')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from .views import *
app_name='accounts'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='accounts/login.html'), name='login'),
    path('register/', registerView.as_view(), name='register'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
]

cart/urls.py
from django.urls import path
from .views import update_cart, view_cart

app_name='cart'

urlpatterns = [
    path('', view_cart, name='view_cart'),
    path('update/<id>', update_cart, name='update_cart'),
]

wineList/urls.py
from django.urls import path
from .views import *
app_name='wineList'
urlpatterns = [
    path('', home, name='home'),
    path('grapes/<slug>', grapes, name='grapes'),
    path('about/', about, name='about'),
    path('contact/', contact, name='contact'),
    path('store/', store, name='store'),
    path('listWine/<slug>', listWine, name='listWine'),
    path('pairing/', pairing, name='pairing'),
]

wineList/models.py
from django.db import models

# Create your models here.

class Wine(models.Model):
    id = models.PositiveIntegerField(primary_key=True)
    country = models.CharField(max_length=200, null=True, blank=True)
    description = models.TextField(max_length=1000, help_text='Enter a brief description')
    designation = models.CharField(max_length=200, null=True, blank=True)
    points = models.CharField(max_length=20, null=True, blank=True)
    price = models.DecimalField(max_digits=20, decimal_places=2, null=True, blank=True)
    province =models.CharField(max_length=200, null=True, blank=True)
    region = models.CharField(max_length=200, null=True, blank=True)
    subregion = models.CharField(max_length=200, null=True, blank=True)
    variety = models.CharField(max_length=200, null=True, blank=True)
    winery = models.CharField(max_length=200, null=True, blank=True)

    def __str__(self):
        # String for representing the model object
        return self.winery

wineList/views.py
from django.db.models import Q
from django.shortcuts import render
from .models import Wine

# Create your views here.
def home(request):
    context={}
    return render(request, 'wineList/home.html', context)

def grapes(request, slug):
    wine =["Cabernet is king in the U.S. and in many other parts of the world. We crave its bold tannins and fruit and it certainly pairs well with many of the dishes we as Americans love: including beef But Cabernet Savignon has a softer side, and goes well with some cheeses and even lavender.", "cabernet.jpg",
         "Merlot is a dark blue-colored wine grape variety, that is used as both a blending grape and for varietal wines. The name Merlot is thought to be a diminutive of merle, the French name for the blackbird, probably a reference to the color of the grape. Its softness, combined with its earlier ripening, makes Merlot a popular grape for blending with the sterner, later-ripening Cabernet Sauvignon, which tends to be higher in tannin", "merlot.jpg",
         "Pinot noir is a red wine grape variety of the species Vitis vinifera. The name may also refer to wines created predominantly from pinot noir grapes. The name is derived from the French words for pine and black. The word pine alludes to the grape variety having tightly clustered, pine cone-shaped bunches of fruit.", "pinot_noir.jpg",
         "Sauvignon blanc is a green-skinned grape variety that originates from the Bordeaux region of France. The grape most likely gets its name from the French words sauvage and blanc due to its early origins as an indigenous grape in South West France. It is possibly a descendant of Savagnin. Sauvignon blanc is planted in many of the world's wine regions, producing a crisp, dry, and refreshing white varietal wine. The grape is also a component of the famous desser wines from Sauternes and Barsac. Sauvignon blanc is widely cultivated in France, Chile, Romania, Canada, Australia, New Zealand, South Africa, the states of Washington and California in the US. Some New World Sauvignon blancs, particularly from California.", "sauvignon_blanc.jpg",
         "Chardonnay is a green-skinned grape variety used in the production of white wine. The variety originated in the Burgundy wine region of eastern France, but is now grown wherever wine is produced, from England to New Zealand. For new and developing wine regions, growing Chardonnay is seen as an easy entry into the international wine market.", "chardonay.jpg", ]
    if slug == 'cabernet':
        context={
            'definition': wine[0],
            'image': wine[1],
        }
    elif slug == 'merlot':
        context={
            'definition': wine[2],
            'image': wine[3],
        }
    elif slug == 'pinotNoir':
        context={
            'definition': wine[4],
            'image': wine[5],
        }
    elif slug == 'sauvignon':
        context={
            'definition': wine[6],
            'image': wine[7],
        }
    elif slug == 'chardonay':
        context={
            'definition': wine[8],
            'image': wine[9],
        }
    return render(request, 'wineList/grapes.html', context)

def about(request):
    context={}
    return render(request, 'wineList/about.html', context)

def contact(request):
    context={}
    return render(request, 'wineList/contact.html', context)

def store(request):
    list_all = Wine.objects.order_by('variety')
    red = list_all.filter( Q(variety='Agiorgitiko') | Q(variety='Aglianico') | Q(variety='Alicante Bouschet') | Q(variety='Alvarinho') | Q(variety='Aragonês') | Q(variety='Baga') | Q(variety='Barbera') | Q(variety='Blauburgunder') | Q(variety='Blaufränkisch') | Q(variety='Bordeaux-style Red Blend') | Q(variety='Cabernet Franc') | Q(variety='Cabernet Sauvignon') | Q(variety='Carignane') | Q(variety='Charbono') | Q(variety='Frappato') | Q(variety='Früburgunder') | Q(variety='G-S-M') | Q(variety='Gamay') | Q(variety='Grenache') | Q(variety='Grenache-Syrah') | Q(variety='Kekfrankos') | Q(variety='Lemberger') | Q(variety='Malbec') | Q(variety='Malbec-Cabernet') | Q(variety='Malbec-Merlot') | Q(variety='Mavrud') | Q(variety='Mencía') | Q(variety='Meritage') | Q(variety='Merlot') | Q(variety='Merlot-Malbec') | Q(variety='Monastrell') | Q(variety='Mourvèdre') | Q(variety='Nebbiolo') | Q(variety='Negrette') | Q(variety="Nero d'Avola") | Q(variety='Petit Verdot') | Q(variety='Petite Sirah') | Q(variety='Pinot Nero') | Q(variety='Pinot Noir') | Q(variety='Pinot Noir-Gamay') | Q(variety='Portuguese Red') | Q(variety='Primitivo') | Q(variety='Provence red blend') | Q(variety='Red Blend') | Q(variety='Rhône-style Red Blend') | Q(variety='Sangiovese') | Q(variety='Syrah') | Q(variety='Syrah-Grenache') | Q(variety='Tannat') | Q(variety='Tannat-Cabernet') | Q(variety='Tempranillo') | Q(variety='Tempranillo Blend') | Q(variety='Tinta de Toro') | Q(variety='Touriga Nacional') | Q(variety='Zinfandel') | Q(variety='St\. Laurent') )
    white = list_all.filter( Q(variety='Alsace white blend') | Q(variety='Assyrtiko') | Q(variety='Bordeaux-style White Blend') | Q(variety='Chardonnay') | Q(variety='Chasselas') | Q(variety='Chenin Blanc-Chardonnay') | Q(variety='Friulano') | Q(variety='Furmint') | Q(variety='Garganega') | Q(variety='Glera') | Q(variety='Godello') | Q(variety='Greco') | Q(variety='Gros Manseng') | Q(variety='Grüner Veltliner') | Q(variety='Malagouzia') | Q(variety='Malvasia Bianca') | Q(variety='Moscato') | Q(variety='Muscat') | Q(variety='Palomino') | Q(variety='Picpoul') | Q(variety='Pinot Bianco') | Q(variety='Pinot Blanc') | Q(variety='Pinot Grigio') | Q(variety='Pinot Gris') | Q(variety='Portuguese White') | Q(variety='Prié Blanc') | Q(variety='Rhône-style White Blend') | Q(variety='Ribolla Gialla') | Q(variety='Riesling') | Q(variety='Sauvignon') | Q(variety='Sauvignon Blanc') | Q(variety='Scheurebe') | Q(variety='Semillon-Sauvignon Blanc') | Q(variety='Silvaner') | Q(variety='Sylvaner') | Q(variety='Torrontés') | Q(variety='Ugni Blanc') | Q(variety='Ugni Blanc-Colombard') | Q(variety='Vermentino') | Q(variety='Viognier') | Q(variety='White Blend'))
    rose = list_all.filter( Q(variety='Gewürztraminer') | Q(variety='Portuguese Rosé') | Q(variety='Rosé'))
    sparkling = list_all.filter( variety='Sparkling Blend')
    fortified = list_all.filter( variety='Sherry')
    list_count = list_all.count()
    red_count = red.count()
    white_count = white.count()
    rose_count = rose.count()
    sparkling_count = sparkling.count()
    fortified_count = fortified.count()
    return render(request, 'wineList/store.html', context = {'list_all': list_all, 'list_count': list_count, 'red': red, 'white': white, 'rose': rose, 'sparkling': sparkling, 'fortified': fortified, 'red_count': red_count, 'white_count': white_count, 'rose_count': rose_count, 'sparkling_count': sparkling_count, 'fortified_count': fortified_count},)

def listWine(request, slug):
    list_all = Wine.objects.order_by('variety')
    red = list_all.filter( Q(variety='Agiorgitiko') | Q(variety='Aglianico') | Q(variety='Alicante Bouschet') | Q(variety='Alvarinho') | Q(variety='Aragonês') | Q(variety='Baga') | Q(variety='Barbera') | Q(variety='Blauburgunder') | Q(variety='Blaufränkisch') | Q(variety='Bordeaux-style Red Blend') | Q(variety='Cabernet Franc') | Q(variety='Cabernet Sauvignon') | Q(variety='Carignane') | Q(variety='Charbono') | Q(variety='Frappato') | Q(variety='Früburgunder') | Q(variety='G-S-M') | Q(variety='Gamay') | Q(variety='Grenache') | Q(variety='Grenache-Syrah') | Q(variety='Kekfrankos') | Q(variety='Lemberger') | Q(variety='Malbec') | Q(variety='Malbec-Cabernet') | Q(variety='Malbec-Merlot') | Q(variety='Mavrud') | Q(variety='Mencía') | Q(variety='Meritage') | Q(variety='Merlot') | Q(variety='Merlot-Malbec') | Q(variety='Monastrell') | Q(variety='Mourvèdre') | Q(variety='Nebbiolo') | Q(variety='Negrette') | Q(variety="Nero d'Avola") | Q(variety='Petit Verdot') | Q(variety='Petite Sirah') | Q(variety='Pinot Nero') | Q(variety='Pinot Noir') | Q(variety='Pinot Noir-Gamay') | Q(variety='Portuguese Red') | Q(variety='Primitivo') | Q(variety='Provence red blend') | Q(variety='Red Blend') | Q(variety='Rhône-style Red Blend') | Q(variety='Sangiovese') | Q(variety='Syrah') | Q(variety='Syrah-Grenache') | Q(variety='Tannat') | Q(variety='Tannat-Cabernet') | Q(variety='Tempranillo') | Q(variety='Tempranillo Blend') | Q(variety='Tinta de Toro') | Q(variety='Touriga Nacional') | Q(variety='Zinfandel') | Q(variety='St\. Laurent') )
    white = list_all.filter( Q(variety='Alsace white blend') | Q(variety='Assyrtiko') | Q(variety='Bordeaux-style White Blend') | Q(variety='Chardonnay') | Q(variety='Chasselas') | Q(variety='Chenin Blanc-Chardonnay') | Q(variety='Friulano') | Q(variety='Furmint') | Q(variety='Garganega') | Q(variety='Glera') | Q(variety='Godello') | Q(variety='Greco') | Q(variety='Gros Manseng') | Q(variety='Grüner Veltliner') | Q(variety='Malagouzia') | Q(variety='Malvasia Bianca') | Q(variety='Moscato') | Q(variety='Muscat') | Q(variety='Palomino') | Q(variety='Picpoul') | Q(variety='Pinot Bianco') | Q(variety='Pinot Blanc') | Q(variety='Pinot Grigio') | Q(variety='Pinot Gris') | Q(variety='Portuguese White') | Q(variety='Prié Blanc') | Q(variety='Rhône-style White Blend') | Q(variety='Ribolla Gialla') | Q(variety='Riesling') | Q(variety='Sauvignon') | Q(variety='Sauvignon Blanc') | Q(variety='Scheurebe') | Q(variety='Semillon-Sauvignon Blanc') | Q(variety='Silvaner') | Q(variety='Sylvaner') | Q(variety='Torrontés') | Q(variety='Ugni Blanc') | Q(variety='Ugni Blanc-Colombard') | Q(variety='Vermentino') | Q(variety='Viognier') | Q(variety='White Blend'))
    rose = list_all.filter( Q(variety='Gewürztraminer') | Q(variety='Portuguese Rosé') | Q(variety='Rosé'))
    sparkling = list_all.filter( variety='Sparkling Blend')
    fortified = list_all.filter( variety='Sherry')
    if slug == 'red':
        context={'wine': red, 'type': slug}
    elif slug == 'white':

wineList/templates/wineList/about.html
{% extends "wineList/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container" id="about">

  <h1>Our Company</h1>
  <p>Freres Wine is an British's Wine Superstore. The country‘s largest independent retailer of fine wine.
    We started in 1996 when the chef Robert Bruce opened a small store in London.
    Today, we operate 193 superstores across 23 states and continue to grow.</p>

  <h1>What we do?</h1>
  <p>We're passionate about wine, and know many of our customers feel the same way.
    So we are committed to offering the nation's best wine selection, with an emphasis on fine wines.
    Our typical store carries more than 8,000 different wines from every wine-producing region in the world.
    The typical Total Wine & More also carries more than 2,500 beers,
    from America‘s most popular brands to hard-to-find microbrews and imports,
    and more than 3,000 different spirits in every style and price range.
    We're also committed to having the lowest prices on wine, spirits and beer every day.
    Our tremendous buying power and special relationships with producers,
    importers and wholesalers bring us considerable savings, which we pass on to our customers.</p>

</div>
{% endblock %}

wineList/templates/wineList/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Wine Wizard</title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.7.2/css/all.css" integrity="sha384-fnmOCqbTlWIlj8LyTjo7mOUStjsKC4pOpQbqyi7RrhN7udi9RwhKkMHpvLbHG9Sr" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Noto+Serif" rel="stylesheet">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href='{% static "wineList/css/bootstrap.min.css" %}'/>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">
    <link rel="stylesheet" href='{% static "wineList/css/carousel.css" %}'/>
    <link rel="stylesheet" href='{% static "wineList/css/blueberry.css" %}'/>
    <link rel="stylesheet" href='{% static "wineList/css/style.css" %}'/>
    {% block jquery %}

    {% endblock %}
  </head>

  <body>
    <div class="container">
      <header>

        <a href="{% url 'wineList:home' %}" id="logo">Freres Wine</a>

        <nav>
          <ul class="navClass" id="nav">
            <li><a href="#">Grapes</a>
                <ul class="sub-menu" id="list">
                  <li><a href="{% url 'wineList:grapes' slug='cabernet' %}">Cabernet</a></li>
                  <li><a href="{% url 'wineList:grapes' slug='merlot' %}">Merlot</a></li>
                  <li><a href="{% url 'wineList:grapes' slug='pinotNoir' %}">Pinot Noir</a></li>
                  <li><a href="{% url 'wineList:grapes' slug='sauvignon' %}">Sauvignon Blanc</a></li>
                  <li><a href="{% url 'wineList:grapes' slug='chardonay' %}">Chardonay</a></li>
                </ul>
            </li>
            <li><a href="{% url 'wineList:store' %}">Store</a></li>
            <li><a href="{% url 'wineList:about' %}">About Us</a></li>
            <li><a href="{% url 'wineList:contact' %}">Contact</a></li>
          </ul>
        </nav>

        <div id="currency">
          {% if user.is_authenticated %}
            <a href="{% url 'accounts:logout' %}"><h6>logout</h6></a>
          {% else %}
            <a href="{% url 'accounts:register' %}">Sign up</a> |
            <a href="{% url 'accounts:login' %}">login</a>
          {% endif %}
          <!--<ul id="flags">
            <li><img src='{% static "wineList/img/usa.png" %}'></img></li>
            <li><img src='{% static "wineList/img/uk.png" %}'></img></li>
            <li><img src='{% static "wineList/img/mexico.png" %}'></img></li>
            <li><img src='{% static "wineList/img/japan.png" %}'></img></li>
            <li><img src='{% static "wineList/img/canada.png" %}'></img></li>
          </ul>-->
        </div>

        <div id="cart">
          <i class="fa fa-shopping-cart" id="cart-img"></i>
          <span class="mini-cart-label">Cart</span>
          <span class="mini-cart-count">0</span>
        </div>

        <div class="col-lg-4" id="cart-window">
          <div  class="container-fluid">
            <div  id="windowHeader">
              <div>
                <h2>Cart</h2>
              </div>
              <div>
                <a href="#" id="closebtn">CLOSE</a>
              </div>
            </div>
            <div>
              <p id="items">Your Cart is empty <span>Continue shopping</span></p>
            </div>
            <div id="total">
              <label>TOTAL</label>
              <input></input>
            </div>
            <div>
              <p>This order price does not include shipping. The shipping cost will be calculated in the next step</p>
            </div>
            <div>
              <button id="buybtn">BUY NOW</button>
            </div>
          </div>
        </div>

      </header>
    </div>

    {% block content %}


    {% endblock %}

    <!--  <footer></footer>     -->
    <footer class="container">
          <div class="row" id="footer-top">
            <div class=" col-lg-3" id="hashtag"><a href="#">#winesomalier</a></div>
            <div class=" col-lg-6" id="footer-logo"><i class="fa fa-gg" id="navlogo"></i></div>
            <div class=" col-lg-3">
              <ul id="social">
                <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li><a href="#"><i class="fa fa-facebook-f"></i></a></li>
                <li><a href="#"><i class="fa fa-pinterest-p"></i></a></li>
                <li><a href="#"><i class="fa fa-instagram"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12" id="copy">
              <p> &copy all rights reserved MGR 2018.<br>
                Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.
                Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
                Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.
              </p>
            </div>
          </div>
          <div class="row">
            <div class="col-lg-12">
              <ul id="pay-mode">
                <li><i class="fa fa-cc-visa"></i></li>
                <li><i class="fa fa-cc-mastercard"></i></li>
                <li><i class="fa fa-cc-amex"></i></li>
                <li><i class="fa fa-cc-paypal"></i></li>
              </ul>
            </div>
          </div>
        </footer>
    <script src='{% static "wineList/javascript/bootstrap.min.js" %}'></script>
    <script src='{% static "wineList/javascript/cartWindow.js" %}'></script>
  </body>
</html>

wineList/templates/wineList/contact.html
{% extends "wineList/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container" id="contact">

  <div>
    <i class="fas fa-phone"></i>
    <h3>Phone</h3>
    <p>Toll-free<br>
      <strong>(678) 678-1234</strong><br>
      Mon-Fri: 9 a.m. - 10 p.m. (ET)<br>
      Sat: 9 a.m. - 8 p.m. (ET)<br>
      Sun: 12 p.m. - 8 p.m. (ET)</p>
  </div>

  <div>
    <i class="fas fa-address-card"></i>
    <h3>Corporate Address</h3>
    <p>Freres Wine<br>
      Attn: Customer Care Center<br>
      6600 Blanco Drive<br>
      London EC2A 4AQ, UK</p>
  </div>

</div>
{% endblock %}

wineList/templates/wineList/grapes.html
{% extends "wineList/base.html" %}
{% load staticfiles %}

{% block content %}
{% static "" as baseUrl %}
<div class="container" id="grapes">
  <p>{{ definition }}</p>
  <div id="image"><img src="{{ baseUrl }}wineList/img/{{ image }}" alt=""></div>
</div>
{% endblock %}

wineList/templates/wineList/home.html
{% extends "wineList/base.html" %}
{% load staticfiles %}


{% block jquery %}
{% include 'wineList/snippet/sliderJquery.html' %}
{% endblock %}

{% block content %}

<section id="slider">
    <div class="row center-lg" id="content">
      <div class="col-lg-12 blueberry">
        <ul class="slides">
          <li><img src='{% static "wineList/img/grapes.jpg" %}'</img></li>
          <li><img src='{% static "wineList/img/landscape.jpg" %}'</img></li>
          <li><img src='{% static "wineList/img/stand.jpg" %}'</img></li>
          <li><img src='{% static "wineList/img/bottles.jpg" %}'</img></li>
        </ul>
      </div>
    </div>
</section>
  <!--  PAIRING   -->
<section id="pairing">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h5>Pairing Your Wine With Food</h5>
        </div>
      </div>
    </div>
    <div class="container">
      <form class="row" method="POST" action="{% url 'wineList:pairing' %}">
        {% csrf_token %}
            <div class="col-lg-2">
              <label>Cheese/nuts</label>
              <select id="cheesNuts" name="1" class="form-control">
                <option selected disabled hidden>Choose here</option>
                <option value="feta">feta</option>
                <option value="pine-nuts">pine nuts</option>
                <option value="asagio">asagio</option>
                <option value="almonds">almonds</option>
                <option value="guoda">guoda</option>
                <option value="peanuts">peanuts</option>
                <option value="brie">brie</option>
                <option value="walnuts">walnuts</option>
                <option value="roquefort">roquefort</option>
                <option value="hazelnuts">hazelnuts</option>
                <option value="parmesan">parmesan</option>
                <option value="cheddar">cheddar</option>
               </select>
            </div>
            <div class="col-lg-2">
              <label>Meat/poultry</label>
              <select id="meatPoultry" name="2" class="form-control">
                <option selected disabled hidden>Choose here</option>
                <option value="chicken">chicken</option>
                <option value="turkey">turkey</option>
                <option value="pork">pork</option>
                <option value="veal">veal</option>
                <option value="duck">duck</option>
                <option value="sausage">sausage</option>
                <option value="lamb">lamb</option>
                <option value="pepperoni">pepperoni</option>
                <option value="beef">beef</option>
                <option value="venison">venison</option>
              </select>
            </div>
            <div class="col-lg-2">
              <label>Seafood</label>
              <select id="seafood" name="3" class="form-control">
                <option selected disabled hidden>Choose here</option>
                <option value="oysters">oysters</option>
                <option value="scallops">scallops</option>
                <option value="lobster">lobster</option>
                <option value="shrimp">shrimp</option>
                <option value="halibut">halibut</option>
                <option value="crab">crab</option>
                <option value="sea-bass">sea bass</option>
                <option value="trout">trout</option>
                <option value="tuna">tuna</option>
                <option value="salmon">salmon</option>
                <option value="grilled-meatier-fish">grilled meatier fish</option>
              </select>
            </div>
            <div class="col-lg-2">
              <label>Veggies</label>
              <select id="fruitsVeggies" name="4" class="form-control">
                <option selected disabled hidden>Choose here</option>
                <option value="asparagus">asparagus</option>
                <option value="potato">potato</option>
                <option value="squash">squash</option>
                <option value="chili-peppers">chili peppers</option>
                <option value="mushrooms">mushrooms</option>
                <option value="beets">beets</option>
                <option value="tomatoes">tomatoes</option>
                <option value="broccoli">broccoli</option>

              </select>
            </div>
            <div class="col-lg-2">
              <label>Fruits</label>
              <select id="herbsSpicesSauces" name="5" class="form-control">
                <option selected disabled hidden>Choose here</option>
                <option value="green-apple">green apple</option>
                <option value="mango">mango</option>
                <option value="pear">pear</option>
                <option value="strawberries">strawberries</option>
                <option value="plums">plums</option>
                <option value="cherries">cherries</option>
              </select>
            </div>
            <div class="col-lg-2">
              <label>Deserts</label>
              <select id="Deserts" name="6" class="form-control">
                <option selected disabled hidden>Choose here</option>
                <option value="key-lime-pie">key lime pie</option>
                <option value="vanilla-pudding">vanilla pudding</option>
                <option value="apple-pie">apple pie</option>
                <option value="creme-brulee">creme brulee</option>
                <option value="coffe-based-desserts">coffe-based desserts</option>
                <option value="fondue">fondue</option>
                <option value="dark-chocolate">dark chocolate</option>
              </select>
            </div>
            <div class="container row" id="pairing-footer">
              <div class="col-lg-2" id="set-btn" >
                <button type="submit" id="pairingBtn">Your Choices</button>
              </div>
              <div class="col-lg-10">
                <p>*Select one meal and obtaine the best wine type to pair with. Or chose a variety of foods and get the rigth wine for that combination.</p>
            </div>
          </div>
        </form>
      </div>
</section>

{% endblock %}

wineList/templates/wineList/listWine.html
{% extends "wineList/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container" id="list-wine">
    <h1 align="center">Chose from our {{ type }} wine collection.<h1>
    {% for w in wine %}
      <div id="wine-section">
        <div id="wine-title">
          <h4>{{w.designation}} {{w.variety}} {{w.winery}}</h4>
          <p class="sub-text">Country: {{w.country}}      Points: {{w.points}}</p>
        </div>
        <div id="price">
          <p class="sub-text">${{w.price}} dollars</p>
        </div>
        <p id="description">{{w.description}}</p>
        <p class="sub-text">Location: {{w.province}}, {{w.region}}, {{w.subregion}}.</p>
        <a href="{% url 'cart:update_cart' id=w.id %}" id="updateCartBtn">Add to Cart</a>
      </div>
    {% endfor %}
</div>
{% endblock %}

wineList/templates/wineList/pairing.html
{% extends "wineList/base.html" %}
{% load staticfiles %}

{% block content %}
<div class="container" id="list-wine">
    <h1 align="center">Pairing Results.</h1>
    <h5 align="center">{% for r in list %} -{{ r }} {% endfor %}</h5>
    {% for obj in result %}
      {% for w in obj %}
      <div id="wine-section">
        <div id="wine-title">
          <h4>{{w.designation}} {{w.variety}} {{w.winery}}</h4>
          <p class="sub-text">Country: {{w.country}}      Points: {{w.points}}</p>
        </div>
        <div id="price">
          <p class="sub-text">${{w.price}} dollars</p>
        </div>
        <p id="description">{{w.description}}</p>
        <p class="sub-text">Location: {{w.province}}, {{w.region}}, {{w.subregion}}.</p>
        <a href="{% url 'cart:update_cart' id=w.id %}" id="updateCartBtn">Add to Cart</a>
      </div>
      {% endfor %}
    {% endfor %}
</div>
{% endblock %}