FreresHeureux/urls.py
from django.contrib import admin
from django.urls import path, include

from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('restaurant.urls', namespace='restaurant')),
    path('wine/', include('wineList.urls', namespace='wineList')),
    path('cart/', include('cart.urls', namespace='cart')),
    path('accounts/', include('accounts.urls', namespace='accounts')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

cart/urls.py
from django.urls import path
from .views import update_cart, view_cart

app_name='cart'

urlpatterns = [
    path('', view_cart, name='view_cart'),
    path('update/<id>', update_cart, name='update_cart'),
]

restaurant/urls.py
from django.urls import path
from.views import HomeTemplateView, reservations

app_name='restaurant'

urlpatterns = [
    path('', HomeTemplateView.as_view(), name='home'),
    path('reservations/', reservations, name='reservations'),
]

restaurant/models.py
from django.db import models
from multiselectfield import MultiSelectField

# Create your models here.
class Guest(models.Model):
    full_name = models.CharField(max_length=50)
    email     = models.EmailField(max_length=100)
    phone     = models.CharField(max_length=15)
    city      = models.CharField(max_length=50)
    state     = models.CharField(max_length=20)
    zip_code  = models.CharField(max_length=10)
    company   = models.CharField(max_length=50)
    booking_info    = models.OneToOneField('BookingInformation', on_delete='CASCADE', null=True, blank=True)   #Strings because they are not defined yet in the script
    payment_info    = models.OneToOneField('PaymentInformation', on_delete='CASCADE', null=True, blank=True)

class BookingInformation(models.Model):
    area = (
        ('Alamo', 'Alamo'),
        ('Capistrano', 'Capistrano'),
        ('San Jose', 'San Jose'),
        ('Espada', 'Espada'),
        ('Terrace', 'Terrace'),
    )
    addServices = (
        ('food', 'food'),
        ('flowers', 'flowers'),
        ('candels', 'candels'),
        ('valet perking', 'valet parking'),
    )
    room                = models.CharField(max_length=15, choices=area)
    reservation_date    = models.DateField()
    purpose   = models.TextField(max_length=1000)
    additional_services = MultiSelectField(choices=addServices, null=True, blank=True)
    special_request = models.TextField(max_length=1000)

class PaymentInformation(models.Model):
    payment = (
        ('debit', 'debit'),
        ('credit','credit'),
    )
    method          = models.CharField(max_length=6, choices=payment)
    name_on_card    = models.CharField(max_length=30)
    card_number     = models.CharField(max_length=20)
    expiration_date = models.DateField()

restaurant/forms.py
from django import forms
#from django.forms import ModelForm
from .models import Guest, BookingInformation, PaymentInformation

class GuestForm(forms.Form):
        full_name = forms.CharField(max_length=50)
        email     = forms.EmailField(max_length=100)
        phone     = forms.CharField(max_length=15)
        city      = forms.CharField(max_length=50)
        state     = forms.CharField(max_length=20)
        zip_code  = forms.CharField(max_length=10)
        company   = forms.CharField(max_length=100)

class BookingInformationForm(forms.Form):
        area = (
            ('Alamo', 'Alamo'),
            ('Capistrano', 'Capistrano'),
            ('San Jose', 'San Jose'),
            ('Espada', 'Espada'),
            ('Terrace', 'Terrace'),
        )
        addServices = (
            ('food', 'food'),
            ('flowers', 'flowers'),
            ('candels', 'candels'),
            ('valet perking', 'valet parking'),
        )
        room                = forms.CharField(max_length=20, widget=forms.Select(choices=area))
        reservation_date    = forms.DateField()
        purpose   = forms.CharField(max_length=1000, widget=forms.Textarea)
        additional_services = forms.CharField(widget=forms.CheckboxSelectMultiple(choices=addServices))
        special_request = forms.CharField(max_length=1000, widget=forms.Textarea)


class PaymentInformationForm(forms.Form):
        payment = (
            ('debit', 'debit'),
            ('credit','credit'),
        )
        method          = forms.CharField(max_length=6, widget=forms.Select(choices=payment))
        name_on_card    = forms.CharField(max_length=50)
        card_number     = forms.CharField(max_length=20)
        expiration_date = forms.DateField()

restaurant/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect
from django.views.generic import TemplateView
from .models import Guest, BookingInformation, PaymentInformation
from .forms import GuestForm, BookingInformationForm, PaymentInformationForm

# Create your views here.
class HomeTemplateView(TemplateView):
    template_name = 'restaurant/home.html'


def reservations(request):
        guest_form  = GuestForm(request.POST or None)
        booking_form = BookingInformationForm(request.POST or None)
        payment_form = PaymentInformationForm(request.POST or None)
        errors = None
        if all([guest_form.is_valid(), booking_form.is_valid(), payment_form.is_valid()]):
            booking = BookingInformation.objects.create(
                room                = booking_form.cleaned_data.get('room'),
                reservation_date    = booking_form.cleaned_data.get('reservation_date'),
                purpose             = booking_form.cleaned_data.get('purpose'),
                additional_services = booking_form.cleaned_data.get('additional_services'),
                special_request     = booking_form.cleaned_data.get('special_request'),
            )
            payment = PaymentInformation.objects.create(
                method          = payment_form.cleaned_data.get('method'),
                name_on_card    = payment_form.cleaned_data.get('name_on_card'),
                card_number     = payment_form.cleaned_data.get('card_number'),
                expiration_date = payment_form.cleaned_data.get('expiration_date'),
            )
            guest = Guest.objects.create(
                full_name = guest_form.cleaned_data.get('full_name'),
                email     = guest_form.cleaned_data.get('email'),
                phone     = guest_form.cleaned_data.get('phone'),
                city      = guest_form.cleaned_data.get('city'),
                state     = guest_form.cleaned_data.get('state'),
                zip_code  = guest_form.cleaned_data.get('zip_code'),
                company   = guest_form.cleaned_data.get('company'),
                booking_info   = booking,
                payment_info   = payment,
            )
            guest.save
            booking.save
            payment.save
            return redirect('home')
        template_name = 'restaurant/reservations.html'
        context = { 'guest_form': guest_form, 'booking_form': booking_form, 'payment_form': payment_form }
        return render(request, template_name, context)

restaurant/templates/restaurant/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Frères Heureux</title>
    {% include 'restaurant/snippet/css.html' %}
  </head>
  <body>
      <div id="biga">
        {% include 'restaurant/snippet/nav.html' %}
      <div id="welcome"><img src='{% static "restaurant/img/welcome.png" %}'></div>
      </div>

      {% block content %}

      {% endblock %}

      {% include 'restaurant/snippet/footer.html' %}
      <script src='{% static "restaurant/javascript/rooms.js" %}'></script>
      <script>
        var mobilMenu = document.getElementById('mobilMenu');
        var nav = document.getElementById('nav');
        var exit = document.getElementById('exit');

        mobilMenu.addEventListener('click', function(e){
          nav.classList.toggle('hide-mobile'); /*Attach and deattach the hede-mobile class from css rules*/
          e.preventDefault();
        });
        exit.addEventListener('click', function(e){
          nav.classList.add('hide-mobile');
          e.preventDefault();
        });
      </script>
  </body>
</html>

restaurant/templates/restaurant/home.html
{% extends 'restaurant/base.html' %}
{% load staticfiles %}

{% block content %}
<div class="bars">
  <h2 align="center">The Chef</h2>
  <div id="chef">
      <img src='{% static "restaurant/img/th2.jpg" %}'>
      <div class="side-text">
        <p>Robert Bruce, a native North Londoner, is well known for his adventuresome, original and creative menus. Recognized early in his career as one to watch among the new rising stars of regional cuisine, Auden brought a worldly fusion of influences to his brand of nouvelle American cuisine. One reviewer declared Roberts’s dishes “extraordinary creations that play havoc with tradition.” His pitch-perfect style brings a lighthearted touch to serious gastronomy, earning his restaurants a loyal fan base of foodies and non-foodies alike for over twenty-five years.</p>
      </div>
  </div>
</div>

<div id="kitchen">
</div>

<div class="bars">
  <h2 align="center">The Food</h2>
    <div id="food">
      <div id="imgFood">
                  <figure>
                    <img src='{% static "restaurant/img/Desserts.jpg" %}'>
                    <figcaption>Deligthful Desserts</figcaption>
                  </figure>
                  <figure>
                    <img src='{% static "restaurant/img/lamb.jpg" %}'>
                    <figcaption>Our speciality, suculent lamb racks.</figcaption>
                  </figure>
                  <figure>
                    <img src='{% static "restaurant/img/pork.jpg" %}'>
                    <figcaption>For the most strict palates, pork shop</figcaption>
                  </figure>
                  <figure>
                    <img src='{% static "restaurant/img/shrimp.jpg" %}'>
                    <figcaption>You can't go wrong with our jumbo shrimp</figcaption>
                  </figure>
      </div>
      <div class="side-text">
                  <p>Robert Bruce, a native North Londoner, is well known for his adventuresome, original and creative menus. Recognized early in his career as one to watch among the new rising stars of regional cuisine, Auden brought a worldly fusion of influences to his brand of nouvelle American cuisine. One reviewer declared Robert’s dishes “extraordinary creations that play havoc with tradition.” His pitch-perfect style brings a lighthearted touch to serious gastronomy, earning his restaurants a loyal fan base of foodies and non-foodies alike for over twenty-five years.</p>
      </div>
    </div>
</div>

<div id="service">
</div>

<div class="bars">
  <h2 align="center">The Rooms</h2>
  <div>
    <div id="space">
      <div class="rooms">
        <h3 id="alamo">Alamo</h3>
        <p>Typical seating arrangement 5 tables of 10. Combines with the next room for larger parties. Views to the amaizing jardins walk, access to semi private jardens terraze.</p>
        <h5>Classroom - 50</h5>
        <h5>Dinning - 50</h5>
        <h5>Reception - 80</h5>
      </div>
      <div class="rooms">
        <h3 id="capis">Capistrano</h3>
        <p>Typical seating arrangement 5 tables of 10. Combines with the next room for larger parties. Views to the amaizing jardins walk, access to semi private jardens terraze.</p>
        <h5>Classroom - 20</h5>
        <h5>Dinning - 20</h5>
        <h5>Imperial Table - 20</h5>
        <h5>Reception - 30</h5>
      </div>
      <div class="rooms">
        <h3 id="jose">San Jose</h3>
        <p>Typical seating arrangement 5 tables of 10. Combines with the next room for larger parties. Views to the amaizing jardins walk, access to semi private jardens terraze.</p>
        <h5>Classroom - 60</h5>
        <h5>Dinning - 60</h5>
        <h5>Reception - 90</h5>
      </div>
      <div class="rooms">
        <h3 id="espada">Espada</h3>
        <p>Typical seating arrangement 5 tables of 10. Combines with the next room for larger parties. Views to the amaizing jardins walk, access to semi private jardens terraze.</p>
        <h5>Classroom - 15</h5>
        <h5>Dinning - 15</h5>
        <h5>Reception - 0</h5>
      </div>
      <div class="rooms">
        <h3 id="terrace">Terrace</h3>
        <p>Typical seating arrangement 5 tables of 10. Combines with the next room for larger parties. Views to the amaizing jardins walk, access to semi private jardens terraze.</p>
        <h5>Classroom - 400</h5>
        <h5>Dinning - 230</h5>
        <h5>Reception - 400</h5>
      </div>
    </div>
    <div>
      <div id="modal"></div>
    </div>
  </div>
</div>
  <hr size="2px" color="black">
{% endblock %}

restaurant/templates/restaurant/reservations.html
{% load staticfiles %}
{% load crispy_forms_tags %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Frères Heureux | Special Events</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href='{% static "restaurant/css/bootstrap.min.css" %}' type="text/css" >
    <link rel="stylesheet" href='{% static "restaurant/css/style.css" %}' />
  </head>
  <body>
    <div id="form-container">
      <a href="{% url 'restaurant:home' %}" id="title-form">Frères Heureux</a>
        <div class="rounded border-0" id="reservation_form">
          <form method="POST" action="">
            {% csrf_token %}
            <div>
              <h1>Guest Information</h1>
              {{ guest_form|crispy }}
            </div>
            <div>
              <h1>Booking Information</h1>
              {{ booking_form.as_p }}
            </div>
            <div>
              <h1>Payment Information</h1>
              {{ payment_form|crispy }}
            </div>
            <input class="btn btn-outline-dark align-center" type="submit" value="RESERVE"></input>
          </form>
        </div>
    </div>
    {% include 'restaurant/snippet/footer.html' %}
  </body>
</html>